name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'  # Toutes les 6 heures
  workflow_dispatch:  # Permet le d√©clenchement manuel

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Sync fork
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream ${{ github.event.repository.source.clone_url }}
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories
          git push origin main
